### ISSUE TITLE
Use a different query to detect all graphs

### ISSUE THREAD

**Issue by JervenBolleman** [JervenBolleman/void-generator#1]
```
SELECT ?G
WHERE {
 GRAPH ?G {}
}
```

**Comment by JervenBolleman** [comment]
I see that RDF4j and virtuoso do not implement this. On the other hand I am not sure this is actually valid.

`{}` creates a binding with no variables set. `?G` would therefore be unset and we should not have a result.

**Comment by galgonek** [comment]
I am absolutely sure that it is valid.
     
The graph pattern `GRAPH ?G subpattern` is evaluated by iterating over all graphs in a dataset (see https://www.w3.org/TR/sparql11-query/#defn_evalGraph):
```
Let R be the empty multiset
foreach IRI g in 'set of graph IRIs':
   R := Union(R, Join( 'solutions of the subpattern in graph g' , Ω(?G->g) )
the result is R
```

The group pattern `{}` matches any graph (including the empty graph) with one solution that does not bind any variables (see https://www.w3.org/TR/sparql11-query/#emptyGroupPattern).

Thus, the pattern `GRAPH ?G {}` should detect all graphs in the dataset.

Unfortunately, it is true that many implementations evaluate GRAPH patterns in violation of the specification. For example, for the following query:

```sparql
select ?g where {
  graph ?g {
    bind (<non_graph_iri> as ?g)
  }
}
```

Virtuoso returns this result:

| ?g |
|---------------|
|<non_graph_iri> |

However, there is no graph whose IRI is `<non_graph_iri>` in the dataset queried!

**Comment by galgonek** [comment]
This is probably a good approach, but its implementation is probably not a priority. IDSM evaluates `SELECT DISTINCT ?G WHERE { GRAPH ?G { ?S ?P ?O } }` in about 40 seconds. In contrast, it evaluates `SELECT ?G WHERE { GRAPH ?G {} }` in about 0.2 seconds. This is quite a big difference, but given how long VoID statistics take to generate, the difference is actually negligible.

**Comment by JervenBolleman** [comment]
@galgonek as this was so trivial, I just did it :)
