### ISSUE TITLE
Possible collision of IRIs of graphs

### ISSUE THREAD

**Issue by galgonek** [JervenBolleman/void-generator#15]
In the `statementsAboutGraph` method, the `graph` IRI is computed as
```
IRI graph = vf.createIRI(voidLocation, "#_graph_" + graphName.getLocalName());
```

Using only local names is not appropriate because, for example, IDSM contains two graphs with the same local name:
```
http://rdf.ncbi.nlm.nih.gov/pubchem/compound
http://rdf.ncbi.nlm.nih.gov/pubchem/descriptor/compound
```

**Comment by JervenBolleman** [comment]
Yes, thank you for this report. Fixed with e2bca171216a2cfe7077f1803ea6fb06c025f40b by taking full IRI in consideration
