### ISSUE TITLE
Crash on empty default graph

### ISSUE THREAD

**Issue by mpagni12** [JervenBolleman/void-generator#9]
With GraphDB running on my localhost, I have populated several named graphs, but I put no data in the default graph. The void-generator works seems to work nicely with the -g option, but it crash without it:

```{bash}
java.lang.NullPointerException: Cannot invoke "org.eclipse.rdf4j.query.Binding.getValue()" because the return value of "org.eclipse.rdf4j.query.BindingSet.getBinding(String)" is nul
```
on commit = 02fd0b1

Maybe the void-generator does not like empty default graph?

   Marco

**Comment by JervenBolleman** [comment]
Fixed by chance with (https://github.com/JervenBolleman/void-generator/commit/7f705af82ea28044cc67476e2ab8e78f64fe531e)
